services:
  app:
    context: .
    dockerfile: .devcontainer/Dockerfile
    # build: .devcontainer/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
